# Generated by Django 4.2.5 on 2023-11-21 11:47

import base.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePlateCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_id', models.CharField(max_length=3)),
                ('plate_name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePlateLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_id', models.CharField(max_length=3)),
                ('plate_name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='Evidences/%y/%m', validators=[base.validators.file_size, django.core.validators.FileExtensionValidator(['mp4'])])),
                ('created', models.CharField(max_length=50, null=True)),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('incident', models.CharField(max_length=12)),
                ('plate_number', models.CharField(max_length=6)),
                ('diplomat_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleplatecd')),
                ('local_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleplatelocal')),
                ('plate_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleregion')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.regions')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VehicleVideo_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload', '-created'],
            },
        ),
        migrations.CreateModel(
            name='TheftMurderVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='Evidences/%y/%m', validators=[base.validators.file_size, django.core.validators.FileExtensionValidator(['mp4'])])),
                ('created', models.CharField(max_length=50, null=True)),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('incident', models.CharField(max_length=6)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.regions')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TheftMurderVideo_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload', '-created'],
            },
        ),
        migrations.CreateModel(
            name='DownloadedVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=50)),
                ('upload', models.CharField(max_length=50)),
                ('incident', models.CharField(max_length=12)),
                ('plate_number', models.CharField(max_length=6)),
                ('download_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(max_length=250)),
                ('diplomat_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleplatecd')),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DownloadedVehicle_downloaded_by', to=settings.AUTH_USER_MODEL)),
                ('local_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleplatelocal')),
                ('plate_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleregion')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.regions')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DownloadedVehicle_uploaded_by', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(default='visited', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.vehiclevideo')),
            ],
            options={
                'ordering': ['-download_time'],
            },
        ),
        migrations.CreateModel(
            name='DownloadedTM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=50)),
                ('upload', models.CharField(max_length=50)),
                ('incident', models.CharField(max_length=6)),
                ('download_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(max_length=150)),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DownloadedTM_downloaded_by', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.regions')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DownloadedTM_uploaded_by', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(default='visited', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.theftmurdervideo')),
            ],
            options={
                'ordering': ['-upload', '-created'],
            },
        ),
        migrations.CreateModel(
            name='DeletedVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='Evidences/Deleted/%y/%m')),
                ('created', models.CharField(max_length=50)),
                ('upload', models.CharField(max_length=50)),
                ('incident', models.CharField(max_length=12)),
                ('plate_number', models.CharField(max_length=6)),
                ('deleted_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(max_length=150)),
                ('number_of_download', models.IntegerField()),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeletedVehicle_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('diplomat_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleplatecd')),
                ('local_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleplatelocal')),
                ('plate_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.vehicleregion')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.regions')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeletedVehicle_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload', '-created'],
            },
        ),
        migrations.CreateModel(
            name='DeletedTM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='Evidences/Deleted/%y/%m')),
                ('created', models.CharField(max_length=50)),
                ('upload', models.CharField(max_length=50)),
                ('incident', models.CharField(max_length=6)),
                ('deleted_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(max_length=150)),
                ('number_of_download', models.IntegerField()),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeletedTM_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.regions')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeletedTM_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload', '-created'],
            },
        ),
    ]
